name: automerge test

on:
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Get List of authors
        id: authors
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = 5;
            const repository = 'utnim2/CI-CD-test';

            async function getCoAuthors() {
              try {
                const commitsResponse = await github.paginate("GET /repos/{owner}/{repo}/pulls/{pull_number}/commits", {
                  owner: repository.split('/')[0],
                  repo: repository.split('/')[1],
                  pull_number: prNumber,
                  per_page: 100,
                });
                
                const authors = commitsResponse
                  .map(data => ({
                    name: data.commit.author.name,
                    email: data.commit.author.email,
                    login: data.commit.author.login,
                    commiter: data.commit.committer
                  })
                  console.log("name": name)
                  console.log("email": email)
                  console.log("login": login)
                  console.log("co_name": committer.name)
                  )
                  .filter(author => author.login !== committer.name)
                  .reduce((uniqueAuthors, author) => {
                    if (!uniqueAuthors.some(a => a.email === author.email)) {
                      uniqueAuthors.push(author);
                    }
                    return uniqueAuthors;
                  }, [])
                  .map(author => `Co-authored-by: ${author.name} <${author.email}>`)
                  .join('\n');
                console.log(authors);
                return authors;
              } catch (error) {
                console.error('Error fetching commits:', error);
                return null;
              }
            }
            
            await getCoAuthors();
