name: automerge test

on:
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Get List of authors
        id: authors
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = 5;
            const repository = 'utnim2/CI-CD-test';

            async function getCoAuthors() {
              try {
                const commitsResponse = await github.paginate("GET /repos/{owner}/{repo}/pulls/{pull_number}/commits", {
                  owner: repository.split('/')[0],
                  repo: repository.split('/')[1],
                  pull_number: prNumber,
                  per_page: 100,
                });
                
                const authors = commitsResponse
                  .map(data => ({
                    name: data.commit.author.name,
                    email: data.commit.author.email,
                    login: data.commit.author.login,
                    commiter: data.commit.committer
                  }))
                  .filter(author => author.email !== commitsResponse[0].commit.author.email)
                  .reduce((uniqueAuthors, author) => {
                    if (!uniqueAuthors.some(a => a.email === author.email)) {
                      uniqueAuthors.push(author);
                    }
                    return uniqueAuthors;
                  }, [])
                  .map(author => `Co-authored-by: ${author.name} <${author.email}>`)
                  .join('\n');
                console.log(authors);
                return authors;
              } catch (error) {
                console.error('Error fetching commits:', error);
                return null;
              }
            }
            
            await getCoAuthors();
      - name: Automerge PR
        uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584 #v0.15.6 https://github.com/pascalgn/automerge-action/releases/tag/v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: "!do-not-merge,ready-to-merge"
          MERGE_METHOD: "squash"
          # Using the output of the previous step (`Co-authored-by: ...` lines) as commit description.
          # Important to keep 2 empty lines as https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line mentions
          MERGE_COMMIT_MESSAGE: "{pullRequest.title} (#{pullRequest.number})\n\n\n${{ steps.authors.outputs.value }}"
          MERGE_RETRIES: "20"
          MERGE_RETRY_SLEEP: "30000"